run:
  timeout: 5m
  build-tags:
  - exclude_graphdriver_btrfs
  - exclude_graphdriver_devicemapper
linters:
  enable:
    - gofmt
    - gci
linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/aws/eks-anywhere-packages)
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-files:
  - "zz_generated.*\\.go$"
  exclude-dirs:
  - ".*/mocks"
  - "controllers/tilt_modules"
