apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eks-anywhere-packages-role
  namespace: eksa-packages
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eks-anywhere-packages-rolebinding
  namespace: eksa-packages
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eks-anywhere-packages-role
subjects:
- kind: ServiceAccount
  name: eks-anywhere-packages-serviceaccount
  namespace: eksa-packages
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-anywhere-packages-serviceaccount
  namespace: eksa-packages
