apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eks-anywhere-packages.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eks-anywhere-packages.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 6ef7a950.eks.amazonaws.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.nsconfigmap.name}}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eks-anywhere-packages.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .Values.namespace }}: {{ include "eks-anywhere-packages.fullname" . }}