apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: PackageBundleController
metadata:
  name: eksa-packages-bundle-controller
  namespace: eksa-packages
spec:
  logLevel: 4
  upgradeCheckInterval: "24h"
  source:
    registry: {{.Values.sourceRegistry}}
    repository: eks-anywhere-packages-bundles
