{{ if .Capabilities.APIVersions.Has "packagecontrollers.packages.eks.amazonaws.com/v1alpha1/{{.Values.clusterName}}" -}}
{{- else -}}
apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: PackageBundleController
metadata:
  name: {{.Values.clusterName}}
  {{- if not .Values.workloadOnly }}
  namespace: eksa-packages
  {{- else }}
  namespace: eksa-packages-{{ .Values.clusterName }}
  {{- end }}
spec:
  upgradeCheckInterval: 24h
  upgradeCheckShortInterval: 5m
  defaultRegistry: {{.Values.defaultRegistry}}
  defaultImageRegistry: {{.Values.defaultImageRegistry}}
  privateRegistry: {{.Values.privateRegistry}}
{{- end -}}
