apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: PackageBundleController
metadata:
  name: {{.Values.clusterName}}
  namespace: eksa-packages
spec:
  bundleRepository: eks-anywhere-packages-bundles
  defaultImageRegistry: {{.Values.sourceRegistry}}
  defaultRegistry: {{.Values.sourceRegistry}}
  upgradeCheckInterval: 24h
  upgradeCheckShortInterval: 1h
