apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: PackageBundle
metadata:
  annotations:
    eksa.aws.com/excludes: LnNwZWMucGFja2FnZXNbXS5zb3VyY2UucmVnaXN0cnkKLnNwZWMucGFja2FnZXNbXS5zb3VyY2UucmVwb3NpdG9yeQo=
    eksa.aws.com/signature: MEUCIQD4irCi3lxXqZlVGC5TKFdha41Y7xC3kblQw+39UWVQgQIgWnyB8fOQVTg8/Z0/mVk6TwOAGLBX1ZoicFYf6vOGuiQ=
  name: v1-22-5
  namespace: eksa-packages
spec:
  packages:
  - name: hello-eks-anywhere
    source:
      registry: public.ecr.aws/eks-anywhere
      repository: hello-eks-anywhere
      versions:
      - digest: sha256:540125e8089d7fd45b7881a6d3d4b19aa8e3048eac91b80700fc0930bb39886d
        name: 0.1.1-f78bf0f83fc6986478cab1336de8c411647c2096
  - name: harbor
    source:
      registry: public.ecr.aws/eks-anywhere
      repository: harbor/harbor-helm
      versions:
      - digest: sha256:9fdf9d04b87ea396c737b4bfecc133dcc4c19e32af0f0e3c3ab8c8beabeacacb
        name: 2.5.0-4324383d8c5383bded5f7378efb98b4d50af827b
