apiVersion: v1
data:
  {{- with .Values.registryMirrorSecret }}
  ENDPOINT: "{{ .endpoint | b64enc }}"
  USERNAME: "{{ .username | b64enc }}"
  PASSWORD: "{{ .password | b64enc }}"
  CACERTCONTENT: "{{ .cacertcontent | b64enc }}"
  {{- end }}
kind: Secret
metadata:
  name: registry-mirror-secret
  namespace: {{ .Values.namespace }}
type: Opaque
