apiVersion: v1
data:
  {{- with .Values.registryMirrorSecret }}
  ENDPOINT: "{{ .endpoint }}"
  USERNAME: "{{ .username }}"
  PASSWORD: "{{ .password }}"
  CACERTCONTENT: "{{ .cacertcontent }}"
  {{- end }}
kind: Secret
metadata:
  name: registry-mirror-secret
  namespace: {{ .Values.namespace }}
type: Opaque
