{{- $render := include "eks-anywhere-packages.rendertype" . }}
{{- if or (eq $render "controller") (eq $render "workload") }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-mirror-secret
  {{- if eq $render "controller" }}
  namespace: {{ .Values.namespace }}
  {{- else if eq $render "workload" }}
  namespace: {{ .Values.namespace }}-{{ .Values.clusterName }}
  {{- end }}
data:
  {{- with .Values.registryMirrorSecret }}
  ENDPOINT: "{{ .endpoint }}"
  USERNAME: "{{ .username }}"
  PASSWORD: "{{ .password }}"
  CACERTCONTENT: "{{ .cacertcontent }}"
  INSECURE: "{{ .insecure }}"
  {{- end }}
type: Opaque
{{- end }}
