apiVersion: v1
kind: Secret
metadata:
  name: registry-mirror-secret
  {{- if not .Values.workloadOnly }}
  namespace: {{ .Values.namespace }}
  {{- else }}
  namespace: {{ .Values.namespace }}-{{ .Values.clusterName }}
  {{- end }}
data:
  {{- with .Values.registryMirrorSecret }}
  ENDPOINT: "{{ .endpoint }}"
  USERNAME: "{{ .username }}"
  PASSWORD: "{{ .password }}"
  CACERTCONTENT: "{{ .cacertcontent }}"
  CERTCONTENT: "{{ .certcontent }}"
  INSECURE: "{{ .insecure }}"
  {{- end }}
type: Opaque
