apiVersion: v1
kind: Secret
metadata:
  name: registry-mirror-secret
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.registryMirrorSecret }}
  ENDPOINT: "{{ .endpoint }}"
  USERNAME: "{{ .username }}"
  PASSWORD: "{{ .password }}"
  CACERTCONTENT: "{{ .cacertcontent }}"
  CERTCONTENT: "{{ .certcontent }}"
  INSECURE: "{{ .insecure }}"
  {{- end }}
type: Opaque
