{{- $render := include "eks-anywhere-packages.rendertype" . }}
{{- if eq $render "controller" }}
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eks-anywhere-packages.fullname" . }}-leader-election-role
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eks-anywhere-packages.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eks-anywhere-packages.fullname" . }}-manager-role
  namespace: {{ .Values.namespace }}-{{ .Values.clusterName }}
  labels:
    {{- include "eks-anywhere-packages.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - delete
{{- end }}
