{{- if not .Values.workloadOnly }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eks-anywhere-packages.labels" . | nindent 4 }}
  {{- if or .Values.additionalAnnotations .Values.serviceAccount.annotations }}
  annotations:
  {{- with .Values.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}