{{- $render := include "eks-anywhere-packages.rendertype" . }}
{{- if eq $render "controller" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-anywhere-packages.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eks-anywhere-packages.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-eks-anywhere-packages-webhook-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eks-anywhere-packages.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: https-webhook
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    control-plane: controller-manager
{{- end }}
